# renew_before_expiry = 30 days
version = 2.10.0
archive_dir = /etc/letsencrypt/archive/iot.thingummy.cc
cert = /etc/letsencrypt/live/iot.thingummy.cc/cert.pem
privkey = /etc/letsencrypt/live/iot.thingummy.cc/privkey.pem
chain = /etc/letsencrypt/live/iot.thingummy.cc/chain.pem
fullchain = /etc/letsencrypt/live/iot.thingummy.cc/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = afe4140e8cca839f1c7267a2ffb20234
authenticator = nginx
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
installer = nginx
[acme_renewal_info]
ari_retry_after = 2026-03-09T09:27:15
