version = 5.2.2
archive_dir = /etc/letsencrypt/archive/practicenight.co.uk
cert = /etc/letsencrypt/live/practicenight.co.uk/cert.pem
privkey = /etc/letsencrypt/live/practicenight.co.uk/privkey.pem
chain = /etc/letsencrypt/live/practicenight.co.uk/chain.pem
fullchain = /etc/letsencrypt/live/practicenight.co.uk/fullchain.pem
[renewalparams]
account = afe4140e8cca839f1c7267a2ffb20234
authenticator = nginx
installer = nginx
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[acme_renewal_info]
ari_retry_after = 2026-03-09T10:23:52
