# renew_before_expiry = 30 days
version = 2.11.0
archive_dir = /etc/letsencrypt/archive/snorkelology.com
cert = /etc/letsencrypt/live/snorkelology.com/cert.pem
privkey = /etc/letsencrypt/live/snorkelology.com/privkey.pem
chain = /etc/letsencrypt/live/snorkelology.com/chain.pem
fullchain = /etc/letsencrypt/live/snorkelology.com/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = afe4140e8cca839f1c7267a2ffb20234
authenticator = nginx
installer = nginx
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[acme_renewal_info]
ari_retry_after = 2026-03-09T09:27:45
