# Redirect HTTP to HTTPS
server {
   listen 80 default_server;
   listen [::]:80 default_server;
   server_name _;

   include /etc/nginx/nginx-config/snippets/bot-protection.conf;

   location / {
       return 301 https://$host$request_uri;
   }
}
