###########################
# PRACTICENIGHT
#    - practicenight.co.uk
###########################

server {
   listen 443 ssl http2;
   listen [::]:443 ssl http2;
   server_name practicenight.co.uk;

   ssl_certificate /etc/letsencrypt/live/snorkelology.co.uk/fullchain.pem; # managed by Certbot
   ssl_certificate_key /etc/letsencrypt/live/snorkelology.co.uk/privkey.pem; # managed by Certbot
   
   # Shared security, bad bot denial, and honeypot traps
   include /etc/nginx/nginx-config/snippets/bot-protection.conf;

   # Regex for common static files
   location ~* \.(?:ico|css|js|gif|jpe?g|png|svg|woff2?|webp|avif)$ {
      add_header Cache-Control "public, no-transform, immutable, max-age=31536000";
      access_log off;
      proxy_pass http://practicenight_backend;
      include snippets/security-headers.conf;
   }

   location / {
      # 1. RATE LIMITING (DoS Protection)
      limit_req zone=global_bot_limit burst=20 nodelay;

      # 2. PROXY CACHE SETTINGS
      proxy_cache my_cache;
      proxy_cache_valid 200 10m;
      proxy_cache_valid 404 1m;

      # 3. HIGH AVAILABILITY (Stale Serving)
      proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;
      proxy_cache_lock on;

      # 4. CACHE BYPASS (For Logged-in Users)
      proxy_cache_bypass $cookie_session;
      proxy_no_cache $cookie_session;

      # 5. SECURITY & PERFORMANCE HEADERS
      include snippets/security-headers.conf;
      add_header X-Cache-Status $snorkel_cache_status_header always;
      add_header Cache-Control $snorkel_dynamic_cache_control always;

      # 6. BACKEND PROXY LOGIC
      proxy_pass http://practicenight_backend;
      include snippets/proxy-headers.conf;

      client_max_body_size 50M;
   }
}
