# renew_before_expiry = 30 days
version = 5.3.1
archive_dir = /etc/letsencrypt/archive/snorkelology.co.uk
cert = /etc/letsencrypt/live/snorkelology.co.uk/cert.pem
privkey = /etc/letsencrypt/live/snorkelology.co.uk/privkey.pem
chain = /etc/letsencrypt/live/snorkelology.co.uk/chain.pem
fullchain = /etc/letsencrypt/live/snorkelology.co.uk/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = afe4140e8cca839f1c7267a2ffb20234
authenticator = nginx
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
installer = nginx
[acme_renewal_info]
ari_retry_after = 2026-03-09T08:29:51
