###########################
# PRACTICENIGHT
#    - practicenight.co.uk
###########################

server {
   listen 443 ssl http2;
   listen [::]:443 ssl http2;
   server_name practicenight.co.uk;

   # Bad Bots Denial
   if ($http_user_agent ~* (Bytespider|ClaudeBot|DotBot|SemrushBot)) {
      return 403;
   }

   ssl_certificate /etc/letsencrypt/live/snorkelology.co.uk/fullchain.pem; # managed by Certbot
   ssl_certificate_key /etc/letsencrypt/live/snorkelology.co.uk/privkey.pem; # managed by Certbot

   # Regex for common static files
   location ~* \.(?:ico|css|js|gif|jpe?g|png|svg|woff2?)$ {
      add_header Cache-Control "public, no-transform, immutable, max-age=31536000";
      access_log off;
      proxy_pass http://192.168.1.136:4005;
      include snippets/security-headers.conf;
   }

   location / {
      # 1. RATE LIMITING (DoS Protection)
      limit_req zone=global_limit burst=20 nodelay;

      # 2. PROXY CACHE SETTINGS
      proxy_cache my_cache;
      proxy_cache_valid 200 1s;
      proxy_cache_valid 404 1m;

      # 3. HIGH AVAILABILITY (Stale Serving)
      proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;
      proxy_cache_lock on;

      # 4. CACHE BYPASS (For Logged-in Users)
      proxy_cache_bypass $http_cookie;
      proxy_no_cache $http_cookie;

      # 5. SECURITY & PERFORMANCE HEADERS
      include snippets/security-headers.conf;
      add_header X-Cache-Status $upstream_cache_status;
      add_header Cache-Control "no-cache, no-store, must-revalidate" always;

      # 6. BACKEND PROXY LOGIC
      proxy_pass http://192.168.1.136:4005;
      include snippets/proxy-headers.conf;

      client_max_body_size 50M;
   }

   # HONEYPOT
   location ~* /(wp-admin|admin|phpmyadmin|setup\.php|\.env) {
      access_log /var/log/nginx/bot_traps.log custom_log;
      return 444;
   }
}
